FROM registry.access.redhat.com/ubi9/python-39

COPY requirements.txt /opt/app-root/src

RUN pip install -U pip && pip install -r requirements.txt

COPY model_server model_server

ENTRYPOINT ["python", "-m", "model_server/model" "--model_dir=https://github.com/RedHatTraining/AI26X-apps/blob/29e7c3f300544c79a905747b4a45b8cc8e23e29e/deploying/serving-apps/sklearn_diabetes_model.joblib"]
